name: ai-pr-reviewer

on:
  pull_request:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}-${{ github.event_name == 'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  main:
    uses: "MaaSTechJapan/ai-pr-reviewer/.github/workflows/main.yaml@main"
    secrets: inherit
